name: CI/CD to EC2 (Apache)
on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # ví dụ: chạy test/build nếu có
      - name: Run unit tests
        run: |
          echo "Run your tests here"

      - name: Archive artifacts
        run: zip -r build.zip . -x ".git/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: build.zip

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site

      - name: Setup SSH
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Copy to EC2 via rsync
        run: |
          unzip build.zip -d site
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i key.pem" \
            --delete site/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/html/

      - name: Restart Apache
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "sudo systemctl restart httpd || sudo systemctl restart apache2"
